#docker build --tag vodstreaming --file dockerfile.vod-streaming .
#docker run -d --rm -e API_URL=http://<IP or DNS of API server>:9090/api -p 9091:9091 vodstreaming

FROM vodbase

RUN lerna bootstrap --scope=@vod/vod-streaming --scope=@vod/vod-auth --scope=@vod/vod-object-storage-client --scope=@vod/vod-redis-client

WORKDIR /app/packages/vod-streaming

EXPOSE 9091
CMD [ "npm", "start" ]