version: '3.3'

services: 

    vod-postgres:
        image: postgres
        container_name: vod-postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "Aa123123"
            POSTGRES_DB: "vod"
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    vod-rabbitmq:
        image: rabbitmq:3-management
        container_name: vod-rabbitmq
        environment: 
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "Aa123123"
        ports:
            - "5672:5672"
            - "15672:15672"

    vod-api:
        build: 
            context: .
            dockerfile: dockerfile.vod-api
        image: vod-api
        container_name: vod-api
        environment: 
            NODE_ENV: "staging"
            PORT: "9090"
            API_URL: "http://vod-api:9090/api"
            DB_USERNAME: "postgres"
            DB_PASSWORD: "Aa123123"
            DB_DATABASE: "vod"
            DB_HOSTNAME: "vod-postgres"
            DB_PORT: "5432"
            RABBITMQ_HOSTNAME: "vod-rabbitmq"
            RABBITMQ_PORT: "5672"
            RABBITMQ_USERNAME: "admin"
            RABBITMQ_PASSWORD: "Aa123123"
        volumes: 
            - persistent-vod:/app/entrypoint
        depends_on: 
            - "vod-rabbitmq"
            - "vod-postgres"
        ports: 
            - "9090:9090"

    vod-streaming:
        build: 
            context: .
            dockerfile: dockerfile.vod-streaming
        image: vod-streaming
        container_name: vod-streaming
        environment: 
            NODE_ENV: "staging"
            PORT: "9091"
            API_URL: "http://vod-api:9090/api"
        depends_on: 
            - "vod-api"
        ports: 
            - "9091:9091"
    
    vod-web:
        build: 
            context: .
            dockerfile: dockerfile.vod-web
        image: vod-web
        container_name: vod-web
        environment: 
            NODE_ENV: "staging"
            PORT: "8080"
            API_URL: "http://vod-api:9090/api"
        depends_on: 
            - "vod-api"
            - "vod-streaming"
        ports: 
            - "80:8080"

    vod-encoder:
        build: 
            context: .
            dockerfile: dockerfile.vod-encoder
        image: vod-encoder
        container_name: vod-encoder
        environment: 
            NODE_ENV: "staging"
            PORT: "8082"
            API_URL: "http://vod-api:9090/api"
            RABBITMQ_HOSTNAME: "vod-rabbitmq"
            RABBITMQ_PORT: "5672"
            RABBITMQ_USERNAME: "admin"
            RABBITMQ_PASSWORD: "Aa123123"
        volumes: 
            - persistent-vod:/app/entrypoint
        depends_on: 
            - "vod-api"
            - "vod-rabbitmq"
        ports: 
            - "8082:8082"

    vod-thumbnailgen:
        build: 
            context: .
            dockerfile: dockerfile.vod-thumbnailgen
        image: vod-thumbnailgen
        container_name: vod-thumbnailgen
        environment: 
            NODE_ENV: "staging"
            PORT: "8083"
            API_URL: "http://vod-api:9090/api"
            RABBITMQ_HOSTNAME: "vod-rabbitmq"
            RABBITMQ_PORT: "5672"
            RABBITMQ_USERNAME: "admin"
            RABBITMQ_PASSWORD: "Aa123123"
        volumes: 
            - persistent-vod:/app/entrypoint
        depends_on: 
            - "vod-api"
            - "vod-rabbitmq"
        ports: 
            - "8083:8083"

    vod-uploader:
        build: 
            context: .
            dockerfile: dockerfile.vod-uploader
        image: vod-uploader
        container_name: vod-uploader
        environment: 
            NODE_ENV: "staging"
            PORT: "8081"
            API_URL: "http://vod-api:9090/api"
            RABBITMQ_HOSTNAME: "vod-rabbitmq"
            RABBITMQ_PORT: "5672"
            RABBITMQ_USERNAME: "admin"
            RABBITMQ_PASSWORD: "Aa123123"
        volumes: 
            - persistent-vod:/app/entrypoint
        depends_on: 
            - "vod-api"
            - "vod-rabbitmq"
        ports: 
            - "8081:8081"

volumes: 
    postgres:
    persistent-vod: