export default [
  {
    key: 'name',
    name: 'בקשה',
    fieldName: 'name',
    minWidth: 50,
    maxWidth: 200,
    isResizable: true,
  },
  {
    key: 'state',
    name: 'מצב',
    fieldName: 'state',
    minWidth: 100,
    maxWidth: 120,
    isResizable: true,
  },
  {
    key: 'comment',
    name: 'תגובה אחרונה',
    fieldName: 'comment',
    minWidth: 50,
    maxWidth: 100,
    isResizable: true,
  },
  {
    key: 'createdAt',
    name: 'תאריך בקשה',
    fieldName: 'createdAt',
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
  },
  {
    key: 'updatedAt',
    name: 'עודכן לאחרונה',
    fieldName: 'updatedAt',
    minWidth: 100,
    maxWidth: 150,
  },
];
