apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: vod-thumbnailgen-deployment
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: vod-thumbnailgen
        spec:
            containers:
              - name: thumbnailgen
                image: vodcontainerregistry.azurecr.io/vod-thumbnailgen
                env:
                    - name: NODE_ENV
                      value: production
                    - name: API_URL
                      value: http://vod-api-service:9090/api
                    - name: RABBITMQ_HOSTNAME
                      value: vod-rabbitmq-service
                    - name: RABBITMQ_PORT
                      value: "5672"
                    - name: RABBITMQ_USERNAME
                      value: admin
                    - name: RABBITMQ_PASSWORD
                      value: Aa123123
                    - name: AWS_ACCESS_KEY_ID
                      value: AKIAJKIJG4M23KDBM22Q     
                    - name: AWS_SECRET_ACCESS_KEY
                      value: 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     
                    - name: AWS_BUCKET
                      value: bucket-vod     
                    - name: AWS_REGION
                      value: eu-central-1
                    - name: TEMP_STORAGE
                      value: \app\entrypoint                                                                                                                            
                volumeMounts:
                    - mountPath: /app/entrypoint
                      name: persistent-vod
            volumes:
                - name: persistent-vod
                  persistentVolumeClaim:
                    claimName: 'persistent-vod'
            imagePullSecrets:
                - name: acr-secret