---
apiVersion: v1
kind: Service
metadata:
    name: vod-streaming-service
    labels:
        app: vod-streaming
spec:
    type: LoadBalancer
    ports:
      - port: 9091
    selector:
        app: vod-streaming
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: vod-streaming-deployment
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: vod-streaming
                service: vod-streaming-service
        spec:
            containers:
              - name: streaming
                image: vodcontainerregistry.azurecr.io/vod-streaming
                ports:
                    - containerPort: 9091
                env:
                    - name: NODE_ENV
                      value: development
                    - name: PORT
                      value: "9091"  
                    - name: API_URL
                      value: http://vod-api-service:9090/api                                                                                                                            