---
apiVersion: v1
kind: Service
metadata:
    name: vod-rabbitmq-service
    labels:
        app: vod-rabbitmq
spec:
    type: LoadBalancer
    ports:
      - name: rabbitmq
        port: 5672
        targetPort: 5672
      - name: rabbitmq-mgmt
        port: 15672    
        targetPort: 15672
    selector:
        app: vod-rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: vod-rabbitmq-deployment
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: vod-rabbitmq
                service: vod-rabbitmq-service
        spec:
            containers:
              - name: rabbitmq
                image: rabbitmq:3-management
                ports:
                    - containerPort: 5672
                    - containerPort: 15672
                env:
                    - name: RABBITMQ_DEFAULT_USER
                      value: admin
                    - name: RABBITMQ_DEFAULT_PASS
                      value: Aa123123