export const SIDEBAR_OPEN_TOGGLE = 'SIDEBAR_OPEN_TOGGLE';
export const CHANNEL_MODAL_OPEN_TOGGLE = 'CHANNEL_MODAL_OPEN_TOGGLE';

export const SET_USER = 'SET_USER';

export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS';
export const SET_UPLOAD_FILE = 'SET_UPLOAD_FILE';
export const SET_UPLOAD_METADATA = 'SET_UPLOAD_METADATA';
export const SET_UPLOAD_STEP = 'SET_UPLOAD_STEP';
export const SET_UPLOAD_VIDEO_SRC = 'SET_UPLOAD_VIDEO_SRC';
export const SET_UPLOAD_VIDEO_THUMBNAILS = 'SET_UPLOAD_VIDEO_THUMBNAILS';
export const SELECT_UPLOAD_VIDEO_THUMBNAIL = 'SELECT_UPLOAD_VIDEO_THUMBNAIL';
export const SET_UPLOAD_VIDEO_NAME = 'SET_UPLOAD_VIDEO_NAME';
export const SET_UPLOAD_VIDEO_DESCRIPTION = 'SET_UPLOAD_VIDEO_DESCRIPTION';
export const SET_UPLOAD_VIDEO_PRIVACY = 'SET_UPLOAD_VIDEO_PRIVACY';
export const SET_UPLOAD_VIDEO_ACL = 'SET_UPLOAD_VIDEO_ACL';

